name: Synergy Admin
main: synergy.admin.SynergyAdmin
version: 0.3.0

permissions:
    warn:
        description: Allows you to warn a user
        default: op
    record:
        description: Allows you to view the record of a user
        default: op
        
commands:
    warn:
        description: Pizza.
        usage: /warn <player> <reason>
        permission: warn
        permission-message: You don't have warn permissions.
    record:
        description: Allows you to view the record of a user
        usage: /record <player>
        permission: record
        permission-message: You don't have record permissions.